module.exports = {
  darkMode: "class",
  content: [
    `components/**/*.{vue,js}`,
    `layouts/**/*.vue`,
    `pages/**/*.vue`,
    `composables/**/*.{js,ts}`,
    `plugins/**/*.{js,ts}`,
    `App.{js,ts,vue}`,
    `app.{js,ts,vue}`,
  ],
  theme: {
    typography: ({ theme }) => ({
      default: {
        css: {
          "--tw-prose-body": theme("colors.text-primary"),
          "--tw-prose-headings": theme("colors.text-primary"),
          "--tw-prose-lead": theme("colors.text-primary"),
          "--tw-prose-links": theme("colors.text-link"),
          "--tw-prose-bold": theme("colors.text-primary"),
          "--tw-prose-counters": theme("colors.pink[600]"),
          "--tw-prose-bullets": theme("colors.text-secondary"),
          "--tw-prose-hr": theme("colors.bg-primary"),
          "--tw-prose-quotes": theme("colors.text-secondary"),
          "--tw-prose-quote-borders": theme("colors.text-secondary"),
          "--tw-prose-captions": theme("colors.text-secondary"),
          "--tw-prose-code": theme("colors.text-secondary"),
          "--tw-prose-pre-code": theme("colors.text-secondary"),
          "--tw-prose-pre-bg": theme("colors.text-secondary"),
        },
      },
    }),
    colors: {
      primary: "var(--color-primary)",
      secondary: "var(--color-secondary)",
      accept: "var(--color-accept)",
      warning: "var(--color-warning)",
      danger: "var(--color-danger)",
      "text-primary": "var(--text-primary)",
      "text-secondary": "var(--text-secondary)",
      "text-active": "var(--text-active)",
      "text-link": "var(--text-link)",
      "bg-primary": "var(--bg-primary)",
      "bg-secondary": "var(--bg-secondary)",
      "bg-tertiary": "var(--bg-tertiary)",
      "bg-quaternary": "var(--bg-quaternary)",
      "button-primary": "var(--button-bg-primary)",
      "button-secondary": "var(--button-bg-secondary)",
    },
    extend: {
      colors: {
        primary: "var(--color-primary)",
        secondary: "var(--color-secondary)",
        accept: "var(--color-accept)",
        warning: "var(--color-warning)",
        error: "var(--color-error)",
        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
        "text-active": "var(--text-active)",
        "text-link": "var(--text-link)",
        "bg-primary": "var(--bg-primary)",
        "bg-secondary": "var(--bg-secondary)",
        "bg-tertiary": "var(--bg-tertiary)",
        "bg-quaternary": "var(--bg-quaternary)",
        "button-primary": "var(--button-bg-primary)",
        "button-secondary": "var(--button-bg-secondary)",
      },
      textColor: {
        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
        "text-active": "var(--text-active)",
        "text-link": "var(--text-link)",
      },
      backgroundColor: {
        "bg-primary": "var(--bg-primary)",
        "bg-secondary": "var(--bg-secondary)",
        "bg-tertiary": "var(--bg-tertiary)",
        "bg-quaternary": "var(--bg-quaternary)",
        "button-primary": "var(--button-bg-primary)",
        "button-secondary": "var(--button-bg-secondary)",
      },
      // colors: {
      //   primary: "var(--color-primary)",
      //   secondary: "var(--color-secondary)",
      //   accept: "var(--color-accept)",
      //   warning: "var(--color-warning)",
      //   danger: "var(--color-danger)",
      //   "text-primary": "var(--text-primary)",
      //   "text-secondary": "var(--text-secondary)",
      //   "text-active": "var(--text-active)",
      //   "text-link": "var(--text-link)",
      //   "bg-primary": "var(--bg-primary)",
      //   "bg-secondary": "var(--bg-secondary)",
      //   "bg-tertiary": "var(--bg-tertiary)",
      //   "bg-quaternary": "var(--bg-quaternary)",
      //   "button-primary": "var(--button-bg-primary)",
      //   "button-secondary": "var(--button-bg-secondary)",
      // },
      fontFamily: {
        comfortaa: ["Comfortaa", "cursive"],
      },
      content: {
        copy: 'url("~/assets/icons/copy.svg")',
      },
    },
  },
};
